TARALLO_URL = "http://192.168.2.142:8080"
TARALLO_TOKEN = "yoLeCHmEhNNseN0BlG0s3A:ksfPYziGg7ebj0goT0Zc7pbmQEIYvZpRTIkwuscAM_k"
TARALLO_FEATURES_AUTO_DOWNLOAD = false

GENERATE_FILES_USE_SUDO = true
GENERATE_FILES_ASK_SUDO_PASSWORD = true

#AUTOMATIC_REPORT_ERRORS = true
#REPORT_URL =
